### ISSUE TITLE
Erro ao rodar o projeto teste para verificar o ambiente.

### ISSUE THREAD

**Issue by edsonlnunes** [MonkeyNights/xamarin-teste-seu-ambiente#1]
Fiz o download do projeto como mandado e testei no VS2017 mas apareceu 4 erros que impediram de iniciar o projeto 35 avisos, podem me ajudar?
![errovs](https://cloud.githubusercontent.com/assets/27029810/24819975/38a3996e-1bbd-11e7-8bc7-4ccb3ec8aea2.png)

**Comment by fabiohsouza** [comment]
@edsonlnunes Você deve Restaurar os Pacotes NuGet para que o VS baixe os pacotes faltantes, como descrito na segunda mensagem de erro da imagem que enviou. 
Para fazer isto clique com o botão direito do mouse em Solução 'HelloMonkey', Restaurar Pacotes NuGet como na imagem:

![restaurarpacotesnuget](https://cloud.githubusercontent.com/assets/1245809/24824152/10bbe350-1bdd-11e7-9b9e-801758bbab0d.png)

Espero que isto resolva o problema.
Abraço

**Comment by wsrzx** [comment]
@edsonlnunes o @fabiohsouza foi preciso na solução do seu problema, por favor verifique se deu tudo certo para que eu feche a issue.

Irei adicionar na documentação a instrução para restauração de pacotes, penso que assim evitaremos de outras pessoas esbarrarem no mesmo problema.

Abraço.
