### ISSUE TITLE
Problemas ao executar.

### ISSUE THREAD

**Issue by Andreyferr** [MonkeyNights/xamarin-teste-seu-ambiente#13]
1>------ Compilação iniciada: Projeto: HelloMonkey.Droid, Configuração: Debug Any CPU ------
1>  Não é possível resolver o conflito entre "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" e "System.Net.Primitives, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Escolhendo "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrariamente.
1>  Considere app.config como remapeamento do assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "4.0.0.0" [] para a Versão "4.1.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll] para solucionar o conflito e obter liberação de aviso.
1>  Considere app.config como remapeamento do assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "3.9.0.0" [] para a Versão "4.0.0.0" [] para solucionar o conflito e obter liberação de aviso.
1>  Considere app.config como remapeamento do assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "1.5.0.0" [] para a Versão "4.0.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] para solucionar o conflito e obter liberação de aviso.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3247: Encontrados conflitos entre versões diferentes do mesmo assembly dependente. No Visual Studio, clique duas vezes nesse aviso (ou selecione-o e pressione Enter) para corrigir os conflitos; ou adicione os seguintes redirecionamentos de associação ao nó "runtime" no arquivo de configuração de aplicativo: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
1>  HelloMonkey.Droid -> C:\Users\Andrey\Documents\Visual Studio 2017\Projects\xamarin-teste-seu-ambiente-master\prj\HelloMonkey\Droid\bin\Debug\HelloMonkey.Droid.dll
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
2>------ Implantação ignorada: Projeto: HelloMonkey.Droid, Configuração: Debug Any CPU ------
2>Não há projeto selecionado para compilar nesta configuração de solução 
========== Compilar: 1 com êxito, 0 com falha, 1 atualizados, 0 ignorados ==========
========== Implantação: 0 com êxito, 0 com falha, 1 ignorados ==========

**Comment by Andreyferr** [comment]
Consegui resolver.

**Comment by jocieldo** [comment]
Por favor, compartilhe a solução. Estou com o mesmo problema. Obrigado.

**Comment by Andreyferr** [comment]
Foi bem simples até. Sou iniciante no Xamarin. So precisei habilitar o Deploy da solução e executar, rodou normal, não precisei configurar a versão 7.1 como falaram em uma das issues abertas.
