### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by allyshoww** [MonkeyNights/xamarin-teste-seu-ambiente#15]
Meus amigos, um grande bom dia!

meu nome é Allyson oliveira e não conheço nada de programação =( e estou me desafiando para ser um devops! 

Quero muito fazer o curso, mas tenho dificuldades e vou superá-las, mas para isso preciso da ajuda do time :)

Eu não sei fazer essa parte, procurei na internet e não achei muita coisa:
--
Execute o aplicativo e na tela inicial clique no botão Buscar, os seus dados serão enviados para a API que vai retornar uma lista com os Monkeys.

Com essas modificações realizadas e o aplicativo rodando, você já terá um ambiente de desenvolvimento pronto para seguir seus estudos com Xamarin.
--
Como faço isso?

**Comment by eliasfpaiva** [comment]
Cara essas coisas é pra fazer no Visual Studio. 

Você baixa o projeto deles extrai do .zip e abre com o  Visual Studio. 

Aí vc acessa esse arquivo e insere seus dados, mas, não se assuste, da dando um monte de erro mesmo.

**Comment by allyshoww** [comment]
Valeu!
