### ISSUE TITLE
InitializeComponent() vs 2015

### ISSUE THREAD

**Issue by rafaelnorajunior** [MonkeyNights/xamarin-teste-seu-ambiente#17]
Estou obtendo erro InitializeComponent() não existe no contexto. Usando o VS 2015

**Comment by eduao** [comment]
Olá @rafaelnorajunior , por mais que o seu issue é da versão 2015, creio que o problema ao ser resolvido no 2017 pode resolver também para o 2015

acompanhe o meu issue, que assim que um tiver a resposta enviamos para o outro, que tal?

[xamarin-teste-seu-ambiente/issues/33](https://github.com/MonkeyNights/xamarin-teste-seu-ambiente/issues/33)

Obrigado! 👍

**Comment by fla07** [comment]
Eu estava tendo o mesmo problema no 2015, da para resolver pelas respostas que o pessoal deu sobre o mesmo problema em outras versões.
