### ISSUE TITLE
Problemas ao executar o emulador

### ISSUE THREAD

**Issue by tiagopedutti** [MonkeyNights/xamarin-teste-seu-ambiente#18]
Eu queria uma ajuda na configuração do emulador, eu estou usando o SDK do Android pra emular, já que o VS Emulator só há disponível até a versão 6.0. Eu nunca programei para mobile, então ainda to meio leigo no assunto...
Então, eu configurei um AVD pra rodar a versão 7.1.1, mas na hora de executar a tela fica preta, se eu tento executar outra versão, aparece apenas "android.
Se eu clicar no debug pra testar o aplicativo, ele apresenta no log **Não há projeto selecionado para compilar nesta configuração de solução**. Porém, se eu for depurar o aplicativo no **HelloMonkey.Droid**, o emulador abre, mas a tela permanece preta e apresenta a mensagem no log: **Aguardando que o emulador fique pronto...**
![screenshot_1](https://cloud.githubusercontent.com/assets/1340024/25066114/4f17eef2-21f3-11e7-9f7f-2b23bb8ebded.png)

**Comment by guiworks** [comment]
Cara, to tendo o mesmo problema. Conseguiu resolver? Minha saída só aparece 'Aguardando que o emulador fique pronto' e a tela fica preta ou com 'Android' escrito.

**Comment by leowsouza** [comment]
Olá !
Não sei se já resolveram, mas o primeiro passo deve ser atualizar o SDK, pois pode ter uma versão mais nova do emulador. Ferramentas, Android, Gerenciador do SDK.
Pode também tentar o emulador da Microsoft:
https://www.visualstudio.com/pt-br/vs/msft-android-emulator/
