### ISSUE TITLE
Erro ao iniciar aplicação

### ISSUE THREAD

**Issue by ghost** [MonkeyNights/xamarin-teste-seu-ambiente#2]
Boa tarde, efetuei as alterações no arquivo especificado, porém ao iniciar a aplicação (portable) a seguinte mensagem de erro aparece:

A project with an output type of class library cannot be started directly.

in order to debug this project, add an executable project to this solution wich references the library project. Set the executable project as the startup project.

Obrigado!

**Comment by ghost** [comment]
![erro](https://cloud.githubusercontent.com/assets/17996394/24830793/255261dc-1c63-11e7-98f8-4960402f9f73.png)

**Comment by wsrzx** [comment]
@LuccasBeckReis você deve definir o projeto Android ou iOS como padrão, botão direito no projeto, set as startup project.

Abraço.
