### ISSUE TITLE
Não há projeto selecionado para compilar nesta configuração de solução 

### ISSUE THREAD

**Issue by roaires** [MonkeyNights/xamarin-teste-seu-ambiente#23]
1>------ Implantação ignorada: Projeto: HelloMonkey.Droid, Configuração: Debug Any CPU ------
1>Não há projeto selecionado para compilar nesta configuração de solução 
========== Implantação: 0 com êxito, 0 com falha, 1 ignorados ==========

Visual Studio 2017 - instalação full

Obrigado

**Comment by JMarquezine** [comment]
Olá aconteceu o mesmo comigo, pesquisei um pouco sobre esse erro e a solução que encontrei foi ir nas propriedades da solução e marcar a opção **Deploy** no projeto .Droid conforme a figura abaixo:
![image](https://cloud.githubusercontent.com/assets/4528163/25111778/6907a34e-23c3-11e7-8550-658558e0f97e.png)

Espero que tenha ajudado!

**Comment by luciano-nascimento** [comment]
Obriado @JMarquezine sua dica funcionou aqui.

**Comment by roaires** [comment]
Obrigado

**Comment by ronalsilva** [comment]
Pra mim esta solução fez o emulador abrir, mas continua dando este erro ""java.exe" foi encerrado com o código 1."

**Comment by DiegoVenancioVieira** [comment]
> Pra mim esta solução fez o emulador abrir, mas continua dando este erro ""java.exe" foi encerrado com o código 1."

Verifique se a compilação não está rodando em modo Release, ao invés de Debug

**Comment by hirios** [comment]
> Olá aconteceu o mesmo comigo, pesquisei um pouco sobre esse erro e a solução que encontrei foi ir nas propriedades da solução e marcar a opção **Deploy** no projeto .Droid conforme a figura abaixo:
> ![image](https://cloud.githubusercontent.com/assets/4528163/25111778/6907a34e-23c3-11e7-8550-658558e0f97e.png)
> 
> Espero que tenha ajudado!

Funcionou aqui!! Agora, pq isso nao vem selecionado por padrão?

**Comment by SebastiaoJunio** [comment]
obrigado
