### ISSUE TITLE
Problemas ao executar o projeto de teste de ambiente

### ISSUE THREAD

**Issue by Elienaldo** [MonkeyNights/xamarin-teste-seu-ambiente#26]
Segui as instruções para execução do projeto de teste de ambiente, mas após executar o projeto nada acontece. Estou executando o projeto Android e o emulador não starta. Percebi que alguns erros e avisos.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	HelloMonkey	C:\Maratona Xamarin\Projects\HelloMonkey\App.xaml	0	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	HelloMonkey	C:\Maratona Xamarin\Projects\HelloMonkey\Views\HelloMonkeyPage.xaml	0	

![image](https://cloud.githubusercontent.com/assets/27690788/25092967/86460cb4-2366-11e7-9a54-2526a63f3eaa.png)

Desde já agradeço.

Att.,
Elienaldo Bittencourt

**Comment by DanielCauser** [comment]
E aí, resolveu?

**Comment by Elienaldo** [comment]
Resolvi sim Daniel. Bastou atualizar a SDK.

Obrigado.


2017-04-23 22:54 GMT-03:00 Daniel John Causer <notifications@github.com>:
