### ISSUE TITLE
Problema na hora de compilar o ambiente xamarin

### ISSUE THREAD

**Issue by fernandok4** [MonkeyNights/xamarin-teste-seu-ambiente#29]
Simplesmente não faz o debug... fala que a compilação foi iniciada... fala que foi bem sucedida e nada acontece

**Comment by luciano-nascimento** [comment]
tente resolver ativando o deploy da solução, vi essa dica no issue #23 e deu certo, segue referência:
https://github.com/MonkeyNights/xamarin-teste-seu-ambiente/issues/23

**Comment by fernandok4** [comment]
Perfeito!!! muito obrigado!

**Comment by americofreitasjr** [comment]
Show! Aqui funcionou também. Obrigado
