### ISSUE TITLE
Nu packages não podem ser restaurados

### ISSUE THREAD

**Issue by ghost** [MonkeyNights/xamarin-teste-seu-ambiente#3]
![image](https://cloud.githubusercontent.com/assets/17996394/24832687/85ab980a-1c8b-11e7-9912-8207944813c9.png)

**Comment by heytherewill** [comment]
O erro está descrito de forma clara: Você está dentro de um diretório que está dentro de muitas pastas (excesso de nesting). Tente mover a sua solução em uma pasta que esteja mais acima na hierarquia para evitar esse problema (`C:/TesteXamarin`, por exemplo).
