### ISSUE TITLE
Error Build action 'EmbeddedResource' is not supported by one or more of the project's targets.

### ISSUE THREAD

**Issue by brunorcajo** [MonkeyNights/xamarin-teste-seu-ambiente#31]
![image](https://cloud.githubusercontent.com/assets/3910730/25158386/703ef98a-247e-11e7-92c9-a97d7b939c4e.png)

Ao executar o emulador não abre, alguém tem alguma idéia do que possa estar acontecendo?

Obrigado

1>------ Build started: Project: HelloMonkey.Droid, Configuration: Debug Any CPU ------
1>  No way to resolve conflict between "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Primitives, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
1>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "4.0.0.0" [] to Version "4.1.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll] to solve conflict and get rid of warning.
1>  Consider app.config remapping of assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "3.9.0.0" [] to Version "4.0.0.0" [] to solve conflict and get rid of warning.
1>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
1>  HelloMonkey.Droid -> D:\REPOSITORIO\PROJETOS\WEB\MARATONA-XAMARIN\WEB\xamarin-teste-seu-ambiente-master\prj\HelloMonkey\Droid\bin\Debug\HelloMonkey.Droid.dll
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
2>------ Skipped Deploy: Project: HelloMonkey.Droid, Configuration: Debug Any CPU ------
2>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========

**Comment by andersonlss** [comment]
Olá Bruno, tudo bem?

Tive o mesmo problema ao abrir o projeto, logo quando instalei o VisualStudio(o meu é o Enterprise 2015).
Resolveu depois de atualizar todos os pacotes para minha versão, que apacere numa bandeirinha no lado superior direito.

Todo caso verifique se VisualStudio está todo atualizado e de um "Clean" e "Build" no Projeto

Mas segue uns Stacks q consultei:
http://stackoverflow.com/questions/37111423/build-action-embeddedresource-is-not-supported-by-one-or-more-of-the-projects
https://forums.xamarin.com/discussion/56559/vs-2015-errors-on-sample-projects

**Comment by brunorcajo** [comment]
Obrigado amigo, acabei de conseguir uma solução aqui, cliquei com o direito na solution e fui em propriedades.
Configuration Properties > Escolha o Projeto Android e marque a opção "Deploy".

Obrigado
Bruno
