### ISSUE TITLE
Erro	CS0103: O nome "InitializeComponent" não existe no contexto atual 

### ISSUE THREAD

**Issue by eduao** [MonkeyNights/xamarin-teste-seu-ambiente#33]
Olá a todos! Observei que ao tentar compilar para testar o ambiente deu este erro para a versão do Android, mesmo sabendo que o App.xaml é um arquivo compartilhado. Observei o atributo 
x:Class="HelloMonkey.App" do arquivo xaml em questão e aparentemente está correto. Porém continua dando o erro do InitializeComponent

Segue o código do App.xaml

```
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="HelloMonkey.App">
    <Application.Resources>
        <!-- Application resource dictionary -->
    </Application.Resources>
</Application>
```

E do seu respectivo App.xaml.cs

```
using Xamarin.Forms;

namespace HelloMonkey
{
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            MainPage = new NavigationPage(new HelloMonkeyPage());
        }

        protected override void OnStart()
        {
            // Handle when your app starts
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }
}
```

> Erro	CS0103	
> O nome "InitializeComponent" não existe no contexto atual	
> HelloMonkey	
> C:\Users\Usuario\Documents\Visual Studio 2017\Projects\HelloMonkey\App.xaml.cs:9	

Como eu poderia corrigir?

Obrigado! 👍

**Comment by eduao** [comment]
Ok gente, resolvi da seguinte forma:

1) Inserindo `using HelloMonkey.Views;` no arquivo `App.xaml.cs`
2) Alterando o parâmetro `x:Class` de `x:Class="HelloMonkey.HelloMonkeyPage"` para `x:Class="HelloMonkey.Views.HelloMonkeyPage"` no arquivo `HelloMonkeyPage.xaml`
3) Alterando o namespace do arquivo `HelloMonkeyPage.xaml.cs` de `namespace HelloMonkey` para `namespace HelloMonkey.Views`

Tentem esta solução no de vocês, por gentileza. Aqui funcionou, porém não tenho como pegar o projeto desde o início no momento para refazer e buscando solucionar para todos os casos.

**Comment by eliasfpaiva** [comment]
Eduao, obrigado por tentar, mas, aqui não adiantou, infelizmente.

**Comment by RuanDelPablo** [comment]
Olá. Consegui resolver este atualizando um componente .Net no pacote Nuget do projeto. 
geriaciar pacotes nuget - Procurar System.ValueTuple Nuget e instalar.
