### ISSUE TITLE
Não acontece Nada

### ISSUE THREAD

**Issue by alexferreiragpe** [MonkeyNights/xamarin-teste-seu-ambiente#38]
Bom dia, coloco para executar compila, mas não acontece nada! O que mais tem que configurar.
![image](https://cloud.githubusercontent.com/assets/10950158/25431258/3490825e-2a56-11e7-9122-87712d636ff8.png)

**Comment by leandropnto** [comment]
O mesmo problema acontece comigo. Cliquei com o botão direito no projeto Droid e selecionei Deploy. O app vai para o celular mas não inicia automaticamente. Você deverá executar manualmente.

**Comment by alexferreiragpe** [comment]
Mas como?

Alex

Em 28/04/2017 7:58 AM, Leandro Pinto <notifications@github.com> escreveu:

O mesmo problema acontece comigo. Cliquei com o botão direito no projeto Droid e selecionei Deploy. O app vai para o celular mas não inicia automaticamente. Você deverá executar manualmente.

**Comment by leandropnto** [comment]
Ah desculpe! Eu to usando o meu celular conectado pelo USB para fazer o deploy. Tem que estar com o modo desenvolvedor ativado no celular. Eu não uso o emulador. Acho muito lento.

**Comment by alexferreiragpe** [comment]
O meu nem compila, da um erro antes. Tô no celular tb

Alex

Em 28/04/2017 8:55 AM, Leandro Pinto <notifications@github.com> escreveu:

Ah desculpe! Eu to usando o meu celular conectado pelo USB para fazer o deploy. Tem que estar com o modo desenvolvedor ativado no celular. Eu não uso o emulador. Acho muito lento.
