### ISSUE TITLE
Problema ambiente Xamarin

### ISSUE THREAD

**Issue by RogerFelipeNsk** [MonkeyNights/xamarin-teste-seu-ambiente#41]
Boa noite senhores, desde a Maratona Xamarin Iniciante, desisti de fazer pois não consigo preparar o ambiente do Visual Studio + Xamarin pra usar e fazer as atividades propostas e acompanhar o desenvolvimento do curso. Então decidi pedir ajuda, ja que agora estou com mais tempo pra acompanhar e participar da maratona. Segue abaixo os erros e busco ajuda para soluciona-los,
Eu moro em Porto Velho - RO, onde eu moro eu só tenho uma internet 4g que mal da pra baixar alguma coisa, então preciso da ajuda dos senhores, pois eu vou na casa de um amigo baixar o que for preciso pra resolver o problema do ambiente.
Agradeço desde ja!

==================================================
Alerta 1
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Aviso		Não foi possível localizar o arquivo 'C:\Users\xxxxxxx\Downloads\xamarin-teste-seu-ambiente-master\xamarin-teste-seu-ambiente-master\prj\HelloMonkey\bin\Release\HelloMonkey.pdb'.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   em Pdb2Mdb.Converter.Convert(String filename)
   em Xamarin.Android.Tasks.ConvertDebuggingFiles.Execute()	HelloMonkey.Droid			
===================================================

Alerta2
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Aviso		The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.dll (v7.1) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.	HelloMonkey.Droid	C:\Users\xxxxxxxxx\Downloads\xamarin-teste-seu-ambiente-master\xamarin-teste-seu-ambiente-master\prj\HelloMonkey\Droid\HelloMonkey.Droid.csproj		

=======================================================
Alerta 3
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Aviso		The $(TargetFrameworkVersion) for FormsViewGroup.dll (v7.1) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.	HelloMonkey.Droid	C:\Users\xxxxxxxx\Downloads\xamarin-teste-seu-ambiente-master\xamarin-teste-seu-ambiente-master\prj\HelloMonkey\Droid\HelloMonkey.Droid.csproj		
==========================================================
Alerta4
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Aviso		The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.Android.dll (v7.1) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.	HelloMonkey.Droid	C:\Users\Nosekim\Downloads\xamarin-teste-seu-ambiente-master\xamarin-teste-seu-ambiente-master\prj\HelloMonkey\Droid\HelloMonkey.Droid.csproj

**Comment by ghost** [comment]
Boa noite amigo! Tente inicialmente encurtar o caminho da pasta do seu projeto e veja se algum erro já é resolvido :)
Faça isso copiando a pasta do projeto HelloDroid para dentro de uma pasta Projetos que você deve criar dentro da partição C:\\

**Comment by RogerFelipeNsk** [comment]
Muito obrigado, deu certo!
Estava com um outro problema tambem mas ja esta resolvido, consegui rodar o ambiente teste do android!

**Comment by ghost** [comment]
Que ótimo! Bons estudos na maratona!
