### ISSUE TITLE
Erro Executar HelloMonkey 

### ISSUE THREAD

**Issue by NeuberFilipe** [MonkeyNights/xamarin-teste-seu-ambiente#44]
Boa tarde pessoa estou com o seguinte erro:

![xamarinhelp](https://cloud.githubusercontent.com/assets/19210039/25720128/2764910a-30e2-11e7-9982-ba1003726eb6.png)

Atenciosamente, 

Neuber Coelho

**Comment by heytherewill** [comment]
O erro é auto-explicativo: Você está tentando executar uma biblioteca. Basta ver que o nome do projeto PCL está em negrito. Para corrigir, clique com o direito no projeto que você quer executar (no seu caso, o `.Droid`) e selecione a opção que o torna o projeto padrão.

**Comment by NeuberFilipe** [comment]
Muito Obrigado. Não tinha prestado atenção.
