### ISSUE TITLE
Não Inicia

### ISSUE THREAD

**Issue by oplesmauricio** [MonkeyNights/xamarin-teste-seu-ambiente#45]
Sigo os passos, porém, vejam a saída:

1>------ Build started: Project: HelloMonkey.Droid, Configuration: Debug Any CPU ------
1>  No way to resolve conflict between "System.Net.Primitives, Version=4.0.0.0, C
1>  ulture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Primitives, 
1>  Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing 
1>  "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f
1>  5f7f11d50a3a" arbitrarily.
1>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, P
1>  ublicKeyToken=b03f5f7f11d50a3a" from Version "4.0.0.0" [] to Version "4.1.0.0
1>  " [F:\Visual Studio\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoA
1>  ndroid\v1.0\Facades\System.Runtime.dll] to solve conflict and get rid of warn
1>  ing.
1>  Consider app.config remapping of assembly "System.Net.Primitives, Culture=neu
1>  tral, PublicKeyToken=b03f5f7f11d50a3a" from Version "3.9.0.0" [] to Version "
1>  4.0.0.0" [] to solve conflict and get rid of warning.
1>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, 
1>  PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [] to Version "4.0.0.
1>  0" [F:\Visual Studio\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Mono
1>  Android\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
1>F:\Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,
1>5): warning MSB3247: Found conflicts between different versions of the same dep
1>endent assembly. In Visual Studio, double-click this warning (or select it and 
1>press Enter) to fix the conflicts; otherwise, add the following binding redirec
1>ts to the "runtime" node in the application configuration file: <assemblyBindin
1>g xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity
1> name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><b
1>indingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentA
1>ssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm
1>.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture=
1>"neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.
1>0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><asse
1>mblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemb
1>lyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d
1>50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /><
1>/dependentAssembly></assemblyBinding>
1>  HelloMonkey.Droid -> C:\Users\Dev\Documents\Visual Studio 2017\Projects\xamar
1>  in-teste-seu-ambiente-master\prj\HelloMonkey\Droid\bin\Debug\HelloMonkey.Droi
1>  d.dll
1>  No way to resolve conflict between "System.Net.Http, Version=4.0.0.0, Culture
1>  =neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=1.5.
1>  0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.
1>  Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbi
1>  trarily.
1>  No way to resolve conflict between "System.Net.Primitives, Version=4.0.0.0, C
1>  ulture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Primitives, 
1>  Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing 
1>  "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f
1>  5f7f11d50a3a" arbitrarily.
1>  Consider app.config remapping of assembly "System.Net.Primitives, Culture=neu
1>  tral, PublicKeyToken=b03f5f7f11d50a3a" from Version "3.9.0.0" [] to Version "
1>  4.0.0.0" [] to solve conflict and get rid of warning.
1>  Consider app.config remapping of assembly "System.Net.Http.Primitives, Cultur
1>  e=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [] to Vers
1>  ion "4.2.29.0" [C:\Users\Dev\Documents\Visual Studio 2017\Projects\xamarin-te
1>  ste-seu-ambiente-master\prj\HelloMonkey\packages\Microsoft.Net.Http.2.2.29\li
1>  b\monoandroid\System.Net.Http.Primitives.dll] to solve conflict and get rid o
1>  f warning.
1>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, 
1>  PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [] to Version "4.0.0.
1>  0" [F:\Visual Studio\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Mono
1>  Android\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
1>F:\Visual Studio\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2125,3)
1>: warning MSB3247: Found conflicts between different versions of the same depen
1>dent assembly. In Visual Studio, double-click this warning (or select it and pr
1>ess Enter) to fix the conflicts; otherwise, add the following binding redirects
1> to the "runtime" node in the application configuration file: <assemblyBinding 
1>xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity n
1>ame="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a"
1> /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></depen
1>dentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-co
1>m:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http.Primitives
1>" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVer
1>sion="0.0.0.0-4.2.29.0" newVersion="4.2.29.0" /></dependentAssembly></assemblyB
1>inding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAsse
1>mbly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken=
1>"b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="
1>4.0.0.0" /></dependentAssembly></assemblyBinding>
1>C:\Users\Dev\Documents\Visual Studio 2017\Projects\xamarin-teste-seu-ambiente-m
1>aster\prj\HelloMonkey\Droid\HelloMonkey.Droid.csproj : warning XA0105: The $(Ta
1>rgetFrameworkVersion) for FormsViewGroup.dll (v7.1) is greater than the $(Targe
1>tFrameworkVersion) for your project (v7.0). You need to increase the $(TargetFr
1>ameworkVersion) for your project.
1>C:\Users\Dev\Documents\Visual Studio 2017\Projects\xamarin-teste-seu-ambiente-m
1>aster\prj\HelloMonkey\Droid\HelloMonkey.Droid.csproj : warning XA0105: The $(Ta
1>rgetFrameworkVersion) for Xamarin.Forms.Platform.Android.dll (v7.1) is greater 
1>than the $(TargetFrameworkVersion) for your project (v7.0). You need to increas
1>e the $(TargetFrameworkVersion) for your project.
1>C:\Users\Dev\Documents\Visual Studio 2017\Projects\xamarin-teste-seu-ambiente-m
1>aster\prj\HelloMonkey\Droid\HelloMonkey.Droid.csproj : warning XA0105: The $(Ta
1>rgetFrameworkVersion) for Xamarin.Forms.Platform.dll (v7.1) is greater than the
1> $(TargetFrameworkVersion) for your project (v7.0). You need to increase the $(
1>TargetFrameworkVersion) for your project.
2>------ Skipped Deploy: Project: HelloMonkey.Droid, Configuration: Debug Any CPU ------
2>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========

E o o app não inicia no emulador...

**Comment by fla07** [comment]
Qual a sua versão do visual studio? Ela está funcionando normalmente, é só o ambiente xamarin que está dando isso?

**Comment by oplesmauricio** [comment]
Oi @fla07 ... Consegui resolver com a dica do issue #6 .... Muito obrigado.......

**Comment by fla07** [comment]
De nada =)
