### ISSUE TITLE
Grupo de Xamarin no Whatsapp

### ISSUE THREAD

**Issue by MiguelPassos** [MonkeyNights/xamarin-teste-seu-ambiente#48]
Para quem interessar, 

Segue um link para grupo de Xamarin no Whats. Não sei quanto aos demais, mas eu não utilizo Twiter e nem Facebook, então achei legal ter um grupo no whats para trocar idéia sobre o tema.

https://chat.whatsapp.com/D8xQQiIDykbDHqpE9KPeW6

Qualquer um é bem vindo.
Se o pessoal do MonkeyNights puder divulgar, acho que seria bacana.

Abraços.

**Comment by andersonnsantos-iexperts** [comment]
@willsb Esse grupo do whatsApp esta ativo ? tentei conectar nesse link e não acessou.
Se tiver outro grupo e puder me passar o convite.
