### ISSUE TITLE
Problemas ao rodar o projeto teste do ambiente

### ISSUE THREAD

**Issue by edsonlnunes** [MonkeyNights/xamarin-teste-seu-ambiente#5]
Já abri uma issue referente ao erro que tava dando e de 4 erros resolveu 1, agora estou com 3 erros.

Fui na opção de Restaurar Pacotes NuGet mas não resolveu todos os erros. Segue em anexo o print dos erros que estão acontecendo ainda.

Se puderem ajudar e me dizer o que fazer para estar com um ambiente pronto para rodar os aplicativos ficarei grato.

OBS: Quando instalei o VS2017 marquei a opção de programação móvel multiplataforma e a opção de Windows Universal.
![errovs](https://cloud.githubusercontent.com/assets/27029810/24842689/7bcbf37a-1d71-11e7-8017-38c54cd14b2b.png)

**Comment by wsrzx** [comment]
@edsonlnunes da uma olhada na resposta do @willsb na issue #3 

Abraço

**Comment by heytherewill** [comment]
Fechando como duplicado.
