### ISSUE TITLE
Compilando, mas não abrindo o emulador Android

### ISSUE THREAD

**Issue by ghost** [MonkeyNights/xamarin-teste-seu-ambiente#6]
![image](https://cloud.githubusercontent.com/assets/17996394/24877653/611c3d9c-1e06-11e7-95a0-4b92e345688d.png)

![image](https://cloud.githubusercontent.com/assets/17996394/24877656/69c1f388-1e06-11e7-9a51-1e85cb01f3d9.png)

Log de Compilação:

1>------ Compilação iniciada: Projeto: HelloMonkey.Droid, Configuração: Debug Any CPU ------
1>  Não é possível resolver o conflito entre "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" e "System.Net.Primitives, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Escolhendo "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrariamente.
1>  Considere app.config como remapeamento do assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "4.0.0.0" [] para a Versão "4.1.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll] para solucionar o conflito e obter liberação de aviso.
1>  Considere app.config como remapeamento do assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "3.9.0.0" [] para a Versão "4.0.0.0" [] para solucionar o conflito e obter liberação de aviso.
1>  Considere app.config como remapeamento do assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "1.5.0.0" [] para a Versão "4.0.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] para solucionar o conflito e obter liberação de aviso.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3247: Encontrados conflitos entre versões diferentes do mesmo assembly dependente. No Visual Studio, clique duas vezes nesse aviso (ou selecione-o e pressione Enter) para corrigir os conflitos; ou adicione os seguintes redirecionamentos de associação ao nó "runtime" no arquivo de configuração de aplicativo: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
1>  HelloMonkey.Droid -> C:\Users\lucca\Desktop\teste\prj\HelloMonkey\Droid\bin\Debug\HelloMonkey.Droid.dll
1>  Não é possível resolver o conflito entre "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" e "System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Escolhendo "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrariamente.
1>  Não é possível resolver o conflito entre "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" e "System.Net.Primitives, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Escolhendo "System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrariamente.
1>  Considere app.config como remapeamento do assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "3.9.0.0" [] para a Versão "4.0.0.0" [] para solucionar o conflito e obter liberação de aviso.
1>  Considere app.config como remapeamento do assembly "System.Net.Http.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "1.5.0.0" [] para a Versão "4.2.29.0" [C:\Users\lucca\Desktop\teste\prj\HelloMonkey\packages\Microsoft.Net.Http.2.2.29\lib\monoandroid\System.Net.Http.Primitives.dll] para solucionar o conflito e obter liberação de aviso.
1>  Considere app.config como remapeamento do assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" da Versão "1.5.0.0" [] para a Versão "4.0.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] para solucionar o conflito e obter liberação de aviso.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2125,3): warning MSB3247: Encontrados conflitos entre versões diferentes do mesmo assembly dependente. No Visual Studio, clique duas vezes nesse aviso (ou selecione-o e pressione Enter) para corrigir os conflitos; ou adicione os seguintes redirecionamentos de associação ao nó "runtime" no arquivo de configuração de aplicativo: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.2.29.0" newVersion="4.2.29.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
2>------ Implantação ignorada: Projeto: HelloMonkey.Droid, Configuração: Debug Any CPU ------
2>Não há projeto selecionado para compilar nesta configuração de solução 
========== Compilar: 1 com êxito, 0 com falha, 1 atualizados, 0 ignorados ==========
========== Implantação: 0 com êxito, 0 com falha, 1 ignorados ==========

**Comment by marcusvnac** [comment]
Olá amigo, este problema está ocorrendo por que o projeto está configurado para compilar para o Android  7.1 (Nougat) e provavelmente você não deve ter essa versão no seu SDK. Você pode atualizar seu SDK ou então alterar o projeto para gerar uma versão que você já tenha instalada. Além disso, também não está selecionada a opção "Deploy" para o projeto Android. Fazendo esses passos o problema será resolvido.

**Comment by wsrzx** [comment]
@LuccasBeckReis valide a resposta do @marcusvnac e notifique para fecharmos a issue =)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/17996394/24885758/ab63567c-1e26-11e7-9ead-bbc3ce9ab019.png)


Funcionou, muito obrigado pela ajuda!

**Comment by DanielCauser** [comment]
No meu caso não precisei alterar a targeted version, apenas marquei o checkbox Deploy.

É assim que se altera a opção de deploy.

O Chekbox da coluna Deploy tem que estar selecionado.

![image](https://cloud.githubusercontent.com/assets/7211075/25321450/024efbae-2885-11e7-8043-3c2ba09f26f8.png)

**Comment by ManoelCamilo** [comment]
Como eu troco a versão do Android do projeto para que não dê o erro relacionado à versão 7.1 (nougat)?
