### ISSUE TITLE
Erro no carregamento do projeto no VS2017

### ISSUE THREAD

**Issue by gilciel** [MonkeyNights/xamarin-teste-seu-ambiente#9]
Amigos estão foram uns dos erros encontrados, voce poderão me ajudar ?

Erro	CS0103	O nome "InitializeComponent" não existe no contexto atual	HelloMonkey	E:\Gilciel\Curso Edx\Microsoft\CursoIntermediario\TstAmb\prj\HelloMonkey\Views\HelloMonkeyPage.xaml.cs	10	Ativo
Erro	CS0006	Arquivo de origem "E:\Gilciel\Curso Edx\Microsoft\CursoIntermediario\TstAmb\prj\HelloMonkey\bin\Debug\HelloMonkey.dll" não pode ser encontrado	HelloMonkey.iOS	E:\Gilciel\Curso Edx\Microsoft\CursoIntermediario\TstAmb\prj\HelloMonkey\iOS\CSC	1	Ativo
Erro		A ação de compilação 'EmbeddedResource' não possui suporte por um ou mais dos destinos do projeto.	HelloMonkey	E:\Gilciel\Curso Edx\Microsoft\CursoIntermediario\TstAmb\prj\HelloMonkey\App.xaml	0

**Comment by wsrzx** [comment]
@gilciel da uma olhada na issue #3

**Comment by wsrzx** [comment]
@gilciel da uma olhada na issue #3

**Comment by wsrzx** [comment]
fechado como duplicado

**Comment by gilciel** [comment]
WillianSRZ, boa noite, fechei o VS2017 e depois abrir e o projeto funcionou ?!?!
Obrigado pela atenção.
